languages = {
    "python":  {
        "Ajenti":  {'lib': ["jadi", "jadi.", "aj", "aj.", "ajenti"], 'counter':  0, 'methods': []},
        "Django-grappelli":  {'lib': ["grappelli"], 'counter':  0, 'methods': []},
        "Django-jet":   {'lib': ["jet"], 'counter':  0, 'methods': []},
        "Django-suit":  {'lib': ["suit"], 'counter':  0, 'methods': []},
        "Django-xadmin":  {'lib': ["xadmin"], 'counter':  0, 'methods': []},
        "Django-allauth":  {'lib': ["allauth"], 'counter':  0, 'methods': []},
        "Django-oauth-provider":  {'lib': ["oauth2_provider"], 'counter':  0, 'methods': []},
        "Django-cms":  {'lib': ["cms"], 'counter':  0, 'methods': []},
        "Django-cacheops":  {'lib': ["cacheops"], 'counter':  0, 'methods': []},
        "Wagtail":  {'lib': ["wagtail"], 'counter':  0, 'methods': []},
        "Flask":  {'lib': ["flask"], 'counter':  0, 'methods': []},
        "Flask-admin":  {'lib': ["flask_admin"], 'counter':  0, 'methods': []},
        "Flask-login":  {'lib': ["flask_login"], 'counter':  0, 'methods': []},
        "Flask-sqlalchemy":  {'lib': ["flask_sqlalchemy"], 'counter':  0, 'methods': []},
        "TimeSide":  {'lib': ["timeside"], 'counter':  0, 'methods': []},
        "Beets":  {'lib': ["beets"], 'counter':  0, 'methods': []},
        "eyeD3":  {'lib': ["eyed3"], 'counter':  0, 'methods': []},
        "Mutagen":  {'lib': ["mutagen"], 'counter':  0, 'methods': []},
        "PyBuilder":  {'lib': ["pybuilder"], 'counter':  0, 'methods': []},
        "Kotti":  {'lib': ["fanstatic"], 'counter':  0, 'methods': []},
        "YAPF":  {'lib': ["yapf"], 'counter':  0, 'methods': []},
        "Celery":  {'lib': ["celery"], 'counter':  0, 'methods': []},
        "Flower":  {'lib': ["flower"], 'counter':  0, 'methods': []},
        "OpenCV":  {'lib': ["cv2"], 'counter':  0, 'methods': []},
        "Eventlet":  {'lib': ["eventlet"], 'counter':  0, 'methods': []},
        "Pandas":  {'lib': ["pandas"], 'counter':  0, 'methods': []},
        "Cryptography":  {'lib': ["cryptography"], 'counter':  0, 'methods': []},
        "Matplotlib":  {'lib': ["matplotlib"], 'counter':  0, 'methods': []},
        "Seaborn":  {'lib': ["seaborn"], 'counter':  0, 'methods': []},
        "NumPy’":  {'lib': ["numpy"], 'counter':  0, 'methods': []},
        "SciPy":  {'lib': ["scipy"], 'counter':  0, 'methods': []},
        "ZODB":  {'lib': ["ZODB"], 'counter':  0, 'methods': []},
        "PyMongo":  {'lib': ["pymongo"], 'counter':  0, 'methods': []},
        "Redis-py":  {'lib': ["redis"], 'counter':  0, 'methods': []},
        "Caffe":  {'lib': ["caffe"], 'counter':  0, 'methods': []},
        "Keras":  {'lib': ["keras"], 'counter':  0, 'methods': []},
        "BeatifulSoup":  {'lib': ["bs4"], 'counter':  0, 'methods': []},
        "Pytorch":  {'lib': ["torch"], 'counter':  0, 'methods': []},
        "TensorFlow":  {'lib': ["tensorflow"], 'counter':  0, 'methods': []},
        "Theano":  {'lib': ["theano"], 'counter':  0, 'methods': []},
        "Sphinx":  {'lib': ["sphinx"], 'counter':  0, 'methods': []}
    },

    "java":  {
        "Spring":  {'lib': ["org.springframework.boot"], 'counter':  0},
        "PrimeFaces":  {'lib': ["org.primefaces"], 'counter':  0},
        "Blade":  {'lib': ["com.bladejava"], 'counter':  0},
        "DropWizard":  {'lib': ["io.dropwizard"], 'counter':  0},
        "Google Web Toolkit":  {'lib': ["com.google.gwt"], 'counter':  0},
        "JavaServer Faces":  {'lib': ["org.apache.myfaces.core"], 'counter':  0},
        "JHipster":  {'lib': ["io.github.jhipster"], 'counter':  0},
        "Spark":  {'lib': ["com.sparkjava"], 'counter':  0},
        "MyBatis":  {'lib': ["org.apache.ibatis"], 'counter':  0},
        "Play":  {'lib': ["com.typesafe.play"], 'counter':  0}
        #  <groupId>org.springframework.boot</groupId>
    },

    "c++":  {
        "Tbox":  {'lib': ["tbox"], 'counter':  0},
        "Libu":  {'lib': ["libu"], 'counter':  0},
        "Openframeworks":  {'lib': ["openframeworks"], 'counter':  0},
        "Cinder":  {'lib': ["cinder"], 'counter':  0},
        "Minizip":  {'lib': ["minizip"], 'counter':  0},
        "LZ4":  {'lib': ["lz4"], 'counter':  0},
        "YAJL":  {'lib': ["yajl"], 'counter':  0},
        "Jansson":  {'lib': ["jansson"], 'counter':  0},
        "Boost":  {'lib': ["boost"], 'counter':  0},
        "QT":  {'lib': ["qt"], 'counter':  0},
        "POCO":  {'lib': ["poco"], 'counter':  0},
        "Mili":  {'lib': ["mili"], 'counter':  0},
        "BDE":  {'lib': ["bde"], 'counter':  0},
        "Juce":  {'lib': ["juce"], 'counter':  0},
    },

    "ruby":  {
        "Rails":  {'lib': ["rails"], 'counter':  0},
        "Hanami":  {'lib': ["hanami"], 'counter':  0},
        "Hamster":  {'lib': ["hamster"], 'counter':  0},
        "Carmen":  {'lib': ["carmen"], 'counter':  0},
        "Mutations":  {'lib': ["mutations"], 'counter':  0},
        "Grape":  {'lib': ["grape"], 'counter':  0},
        "Roda":  {'lib': ["roda"], 'counter':  0},
        "Sinatra":  {'lib': ["sinatra"], 'counter':  0},
        "Padrino":  {'lib': ["padrino"], 'counter':  0},
        "Cuba":  {'lib': ["cuba"], 'counter':  0},
        "Goliath":  {'lib': ["goliath"], 'counter':  0},
        "Scorched":  {'lib': ["scorched"], 'counter':  0},
        "Pakyow":  {'lib': ["pakyow"], 'counter':  0},
        "Trailblazer":  {'lib': ["trailblazer"], 'counter':  0},
        "Ramaze":  {'lib': ["ramaze"], 'counter':  0},
    },

    "javascript":  {
        "Angular":  {'lib': ["ajax.googleapis.com/ajax/libs/angular/"], 'counter':  0},
        "React":  {'lib': ["React"], 'counter':  0},
        "Vue.js":  {'lib': ["cdnjs.cloudflare.com/ajax/libs/vue", ".vue"], 'counter':  0},
        "Ember.js":  {'lib': ["ember.js", "ember-data.js"], 'counter':  0},
        "Meteor":  {'lib': ["Meteor."], 'counter':  0},
        "Mithril":  {'lib': ["mithril.js"], 'counter':  0},
        "Node.js":  {'lib': ["node-static"], 'counter':  0},
        "Aurelia":  {'lib': ["aurelia-core", "aurelia-bootstrapper"], 'counter':  0},
        "Backbone.js":  {'lib': ["backbone.js"], 'counter':  0},
        "jQuerry":  {'lib': ["jquery.js", "ajax.googleapis.com/ajax/libs/jquery "], 'counter':  0}
    },

    "go":  {
        "Testify":  {'lib': ["github.com/stretchr/testify"], 'counter':  0},
        "Kubernetes":  {'lib': ["k8s.io/client-go/kubernetes"], 'counter':  0},
        "Ginkgo":  {'lib': ["github.com/onsi/ginkgo/ginkgo"], 'counter':  0},
        "Gomega":  {'lib': ["github.com/onsi/gomega"], 'counter':  0},
        "Logrus":  {'lib': ["github.com/sirupsen/logrus"], 'counter':  0},
        "Glog":  {'lib': ["github.com/google/glog"], 'counter':  0},
        "Gocheck ":  {'lib': ["gopkg.in/check.v1"], 'counter':  0},
        "AWS SDK":  {'lib': ["github.com/aws/aws-sdk-go"], 'counter':  0},
        "Errors":  {'lib': ["github.com/juju/errors"], 'counter':  0},
        "Cobra":  {'lib': ["github.com/spf13/cobra"], 'counter':  0},
        "Revel":  {'lib': ["github.com/revel/cmd/revel"], 'counter':  0},
        "Gin":  {'lib': ["github.com/gin-gonic/gin"], 'counter':  0},
        "Martini":  {'lib': ["github.com/go-martini/martini"], 'counter':  0},
        "Web.go":  {'lib': ["github.com/hoisie/web"], 'counter':  0},
        "Gorilla":  {'lib': ["github.com/gorilla/mux"], 'counter':  0},
        "Goji":  {'lib': ["github.com/zenazn/goji"], 'counter':  0},
        "Beego":  {'lib': ["github.com/astaxie/beego"], 'counter':  0}
    },

    "php":  {
        "Laravel5":  {'lib': ["laravel/framework"], 'counter':  0},
        "Laravel Tinker":  {'lib': ["laravel/tinker"], 'counter':  0},
        "TrustedProxy":  {'lib': ["fideloper/proxy"], 'counter':  0},
        "Jwt-auth":  {'lib': ["tymon/jwt-auth"], 'counter':  0},
        "Laravel Dump Server":  {'lib': ["beyondcode/laravel-dump-server"], 'counter':  0},
        "Faker":  {'lib': ["fzaninotto/faker"], 'counter':  0},
        "Mockery":  {'lib': ["mockery/mockery"], 'counter':  0},
        "Collision":  {'lib': ["nunomaduro/collision"], 'counter':  0},
        "CakePHP Chronos":  {'lib': ["cakephp/chronos"], 'counter':  0},
        "CakePHP Code Sniffer":  {'lib': ["cakephp/cakephp-codesniffer"], 'counter':  0},
        "Zend-diactoros":  {'lib': ["zendframework/zend-diactoros"], 'counter':  0},
        "Aura.Intl":  {'lib': ["aura/intl"], 'counter':  0},
        "Yii extension installer":  {'lib': ["yiisoft/yii2-compose"], 'counter':  0},
        "HTML Purifier":  {'lib': ["ezyang/htmlpurifier"], 'counter':  0},
        "PHP Coding Standards Fixer":  {'lib': ["friendsofphp/php-cs-fixer"], 'counter':  0},
        "phpunit-speedtrap":  {'lib': ["johnkary/phpunit-speedtrap"], 'counter':  0},
        "Markdown parser for PHP":  {'lib': ["cebe/markdown"], 'counter':  0},
        "Yii2":  {'lib': ["yiisoft/yii2"], 'counter':  0},
        "Indent":  {'lib': ["cebe/indent"], 'counter':  0},
    },

    "swift":  {
        "Viperit":  {'lib': ["Viperit", "Viperit."], 'counter':  0},
        "RandomUserSwift":  {'lib': ["RandomUserSwift", "RandomUserSwift."], 'counter':  0},
        "LoginKit":  {'lib': ["LoginKit", "LoginKit."], 'counter':  0},
        "Telegrammer":  {'lib': ["Telegrammer", "Telegrammer."], 'counter':  0},
        "MessengerKit":  {'lib': ["MessengerKit", "MessengerKit"], 'counter':  0},
        "UIKit":  {'lib': ["UIKit", "UIKit."], 'counter':  0},
        "SwiftCLI":  {'lib': ["SwiftCLI", "SwiftCLI."], 'counter':  0},
        "Graph":  {'lib': ["Graph", "Graph."], 'counter':  0},
        "Freddy":  {'lib': ["Freddy", "Freddy."], 'counter':  0},
        "Elevate":  {'lib': ["Elevate", "Elevate."], 'counter':  0},
        "Disk":  {'lib': ["Disk", "Disk."], 'counter':  0},
        "SQLite":  {'lib': ["SQLite", "SQLite."], 'counter':  0},
        "AEXML":  {'lib': ["AEXML", "AEXML."], 'counter':  0},
        "Yams":  {'lib': ["Yams", "Yams."], 'counter':  0},
        "Zip":  {'lib': ["Zip", "Zip."], 'counter':  0},
        "Cleanse":  {'lib': ["Cleanse", "Cleanse."], 'counter':  0},
        "Bond":  {'lib': ["Bond", "Bond."], 'counter':  0},
        "ReactiveCocoa":  {'lib': ["ReactiveCocoa", "ReactiveCocoa."], 'counter':  0},
        "PeekPop":  {'lib': ["PeekPop", "PeekPop."], 'counter':  0},
        "Bluejay":  {'lib': ["Bluejay", "Bluejay."], 'counter':  0},
        "GPUImage":  {'lib': ["GPUImage", "GPUImage."], 'counter':  0},
        "Nuke":  {'lib': ["Nuke", "Nuke."], 'counter':  0},
        "Neon":  {'lib': ["Neon", "Neon."], 'counter':  0},
        "Localize_Swift":  {'lib': ["Localize_Swift", "Localize_Swift."], 'counter':  0},
        "LocoKit":  {'lib': ["LocoKit", "LocoKit."], 'counter':  0},
        "ResponseDetective":  {'lib': ["ResponseDetective", "ResponseDetective."], 'counter':  0},
        "BlueSocket":  {'lib': ["BlueSocket", "BlueSocket."], 'counter':  0},
        "Vapor":  {'lib': ["Vapor", "Vapo."], 'counter':  0},
        "Kitura":  {'lib': ["Kitura", "Kitura."], 'counter':  0}
    },

    "kotlin":  {
        "Wasabi":  {'lib': ["org.wasabifx.wasabi"], 'counter':  0},
        "Ktor":  {'lib': ["io.ktor"], 'counter':  0},
        "Yested":  {'lib': ["net.yested"], 'counter':  0},
        "Hexagon":  {'lib': ["com.hexagonkt"], 'counter':  0},
        "Glimpse framework":  {'lib': ["org.glimpseframework"], 'counter':  0},
        "Async Under 8":  {'lib': ["async_under8"], 'counter':  0},
        "TornadoFX":  {'lib': ["no.tornado"], 'counter':  0},
        "Kotlin-nosql":  {'lib': ["org.jetbrains.kotlin"], 'counter':  0}
    },

    "scala":  {
        "ScalaTest":  {'lib': ["org.scalatest."], 'counter':  0},
        "Specs2":  {'lib': ["org.specs2"], 'counter':  0},
        "ScalaCheck":  {'lib': ["org.scalacheck"], 'counter':  0},
        "Akka":  {'lib': ["com.typesave.akka"], 'counter':  0},
        "Cats":  {'lib': ["cats."], 'counter':  0},
        "Mongo":  {'lib': ["org.mongodb.scala"], 'counter':  0},
        "Play":  {'lib': ["play.api.libs"], 'counter':  0},
        "Finch":  {'lib': ["io.finch"], 'counter':  0},
        "BlueEyes":  {'lib': ["com.github.jdegoes"], 'counter':  0},
        "Slick":  {'lib': ["slick.driver"], 'counter':  0},
        "Scalatra":  {'lib': ["org.scalatra"], 'counter':  0},
        "Json4s":  {'lib': ["org.json4s"], 'counter':  0},
        "ScalikeJDBC":  {'lib': ["org.scalikejdbc"], 'counter':  0}
    },
}
